// <auto-generated />
using System;
using HastaneOtomasyonSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HastaneOtomasyonSistemi.Migrations
{
    [DbContext(typeof(HastaneOtomasyonSistemiContext))]
    partial class HastaneOtomasyonSistemiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Doktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("poliklinikId")
                        .HasColumnType("int");

                    b.Property<string>("soyAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("poliklinikId");

                    b.ToTable("Doktor");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Hasta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("soyAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hasta");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Hastaneler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("HastaneAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ilId")
                        .HasColumnType("int");

                    b.Property<int>("ilceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ilId");

                    b.HasIndex("ilceId");

                    b.ToTable("Hastaneler");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ilAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("il");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ilId")
                        .HasColumnType("int");

                    b.Property<string>("ilceAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ilId");

                    b.ToTable("ilce");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.poliklinik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PoliklinikIsmi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hastaneId")
                        .HasColumnType("int");

                    b.Property<int>("ilId")
                        .HasColumnType("int");

                    b.Property<int>("ilceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("hastaneId");

                    b.HasIndex("ilId");

                    b.HasIndex("ilceId");

                    b.ToTable("poliklinik");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Randevu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("RandevuDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("doktorId")
                        .HasColumnType("int");

                    b.Property<int>("hastaId")
                        .HasColumnType("int");

                    b.Property<int>("hastaneId")
                        .HasColumnType("int");

                    b.Property<int>("ilId")
                        .HasColumnType("int");

                    b.Property<int>("ilceId")
                        .HasColumnType("int");

                    b.Property<int>("poliklinikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("doktorId");

                    b.HasIndex("hastaId");

                    b.HasIndex("hastaneId");

                    b.HasIndex("ilId");

                    b.HasIndex("ilceId");

                    b.HasIndex("poliklinikId");

                    b.ToTable("Randevu");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Doktor", b =>
                {
                    b.HasOne("HastaneOtomasyonSistemi.Models.poliklinik", "poliklinik")
                        .WithMany("doktorlar")
                        .HasForeignKey("poliklinikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("poliklinik");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Hastaneler", b =>
                {
                    b.HasOne("HastaneOtomasyonSistemi.Models.il", "il")
                        .WithMany()
                        .HasForeignKey("ilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneOtomasyonSistemi.Models.ilce", "ilce")
                        .WithMany("hastaneler")
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("il");

                    b.Navigation("ilce");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.ilce", b =>
                {
                    b.HasOne("HastaneOtomasyonSistemi.Models.il", "il")
                        .WithMany("ilceler")
                        .HasForeignKey("ilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("il");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.poliklinik", b =>
                {
                    b.HasOne("HastaneOtomasyonSistemi.Models.Hastaneler", "hastaneler")
                        .WithMany("poliklinikler")
                        .HasForeignKey("hastaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneOtomasyonSistemi.Models.il", "il")
                        .WithMany()
                        .HasForeignKey("ilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneOtomasyonSistemi.Models.ilce", "ilce")
                        .WithMany()
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hastaneler");

                    b.Navigation("il");

                    b.Navigation("ilce");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Randevu", b =>
                {
                    b.HasOne("HastaneOtomasyonSistemi.Models.Doktor", "doktor")
                        .WithMany()
                        .HasForeignKey("doktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneOtomasyonSistemi.Models.Hasta", null)
                        .WithMany("Randevular")
                        .HasForeignKey("hastaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneOtomasyonSistemi.Models.Hastaneler", "hastaneler")
                        .WithMany()
                        .HasForeignKey("hastaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneOtomasyonSistemi.Models.il", "il")
                        .WithMany()
                        .HasForeignKey("ilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneOtomasyonSistemi.Models.ilce", "ilce")
                        .WithMany()
                        .HasForeignKey("ilceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaneOtomasyonSistemi.Models.poliklinik", "poliklinik")
                        .WithMany()
                        .HasForeignKey("poliklinikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doktor");

                    b.Navigation("hastaneler");

                    b.Navigation("il");

                    b.Navigation("ilce");

                    b.Navigation("poliklinik");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Hasta", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.Hastaneler", b =>
                {
                    b.Navigation("poliklinikler");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.il", b =>
                {
                    b.Navigation("ilceler");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.ilce", b =>
                {
                    b.Navigation("hastaneler");
                });

            modelBuilder.Entity("HastaneOtomasyonSistemi.Models.poliklinik", b =>
                {
                    b.Navigation("doktorlar");
                });
#pragma warning restore 612, 618
        }
    }
}
